"""added new fields to Customer

Revision ID: 5b3940d6499e
Revises: 
Create Date: 2025-01-05 13:27:05.100750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3940d6499e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('construction_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rate_of_construction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wall_compound_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rate_of_wall_compound', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('rate_of_wall_compound')
        batch_op.drop_column('wall_compound_size')
        batch_op.drop_column('rate_of_construction')
        batch_op.drop_column('construction_size')

    # ### end Alembic commands ###
